title: "Domain Shortner"

#Do you want to redirect the root?
#Example www.7bl.ink redirects to www.7blink.com
#Whereas all other links will begin with "www.7bl.ink/#" followed by the short name.
root: "http://www.7blink.com"
rootRedirect: true

#Short domains main url, used as prefix for all links in /add
url: "http://www.7bl.ink"

#Add new link redirect.  This should be a link to the short.csv git page.
add: "https://github.com/7blink/name-shortener/blob/gh-pages/_data/short.csv"


readme: "https://github.com/7blink/name-shortener/blob/gh-pages/README.md"

analytics: "
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80710685-1', 'auto');
  ga('send', 'event', 'URLshortener', 'redirect', page);
"

